INSERT INTO `QUESTIONNAIRES` (`nom_questionnaire`) VALUES
('7 sommets les plus haut du monde');

INSERT INTO `QUESTIONS` (`intitule`, `nom_questionnaire`, `latitude`, `longitude`,`titre_carousel`, `information1`, `information2`, `information3`) VALUES
('Localisez le Mont Everest', '7 sommets les plus haut du monde', 27.9845683, 86.92575929999998, "L’Everest, en tibétain Qomolangma ou encore Chomolungma, en népalais, aussi appelé mont Everest, est une montagne située dans la chaîne de l'Himalaya, à la frontière entre le Népal (Sagarmatha) et la Chine (Tibet).", "Il est aperçu par des Européens pour la première fois en 1847 puis, après quelques années d'observations et de calculs, son altitude est établie à 8 848 mètres et il est identifié comme le plus haut sommet du monde au-dessus du niveau de la mer.", "Cette caractéristique lui vaut d'être baptisé de son nom actuel par les Occidentaux en 1865 et, dès les années 1920, de lui attirer l'intérêt des alpinistes qui se lancent à l'assaut de ses pentes. Plusieurs expéditions, en particulier britanniques, se succèdent depuis le nord. Toutefois, les conditions climatiques extrêmes font leurs premières victimes, parmi lesquelles George Mallory et Andrew Irvine, en 1924, dont on ne saura probablement jamais avec certitude s'ils ont atteint le sommet.", "Image/7 sommets les plus haut du monde/img_q1"),
('Localisez le Cerro Aconcagua', '7 sommets les plus haut du monde', -32.653179, -70.01086750000002, "L'Aconcagua est un sommet d'Argentine situé à treize kilomètres de la frontière chilienne et s'élevant à 6 962 mètres d'altitude. Surnommé le « colosse de l'Amérique », il constitue le point culminant de la cordillère des Andes et la plus haute montagne en dehors de l'Asie.", "Il domine un vaste parc provincial protégeant des espèces animales typiques de la cordillère, en particulier le condor des Andes et le guanaco, ainsi qu'une végétation rare et fragile. En effet, le climat est aride et la couverture neigeuse ténue, malgré l'existence de quelques glaciers modestes.", "Son ascension est relativement aisée pour des personnes acclimatées à l'altitude, malgré des phénomènes venteux parfois violents. Aussi la montagne semble avoir été occupée très tôt par des populations quechuas. La première ascension officielle est réalisée par le Suisse Matthias Zurbriggen en 1897 par la face Nord.", "Image/7 sommets les plus haut du monde/img_q2"),
('Localisez le McKinley (Denali)', '7 sommets les plus haut du monde', 63.06916889999999, -151.00698420000003, "Le Denali, anciennement mont McKinley, est la plus haute montagne d'Amérique du Nord. Situé au centre de l'Alaska, aux États-Unis, il culmine à 6 190 mètres d'altitude.", "Son altitude, son climat extrême et sa situation géographique arctique en font un des sommets les plus difficiles à escalader au monde et ce n'est qu'en 1913 qu'il fut pour la première fois escaladé par un être humain. Depuis 1917, la montagne fait partie de la zone protégée du parc national de Denali.", "Denali signifie « celui qui est haut » en koyukon, une langue athapascane. Toutefois, en 1896, la montagne est officiellement appelée mont McKinley, d'après l'ancien gouverneur de l'Ohio et futur président des États-Unis William McKinley.", "Image/7 sommets les plus haut du monde/img_q3"),
('Localisez le Kilimandjaro', '7 sommets les plus haut du monde', -3.067424699999999, 37.355627299999924, "Le Kilimandjaro ou Kilimanjaro est une montagne située dans le Nord-Est de la Tanzanie et composée de trois volcans éteints : le Shira à l'ouest, culminant à 3 962 mètres d'altitude, le Mawenzi à l'est, s'élevant à 5 149 mètres d'altitude, et le Kibo, le plus récent géologiquement, situé entre les deux autres et dont le pic Uhuru à 5 891,8 mètres d'altitude constitue le point culminant de l'Afrique.", " Outre cette caractéristique, le Kilimandjaro est connu pour sa calotte glaciaire sommitale en phase de retrait accéléré depuis le début du xxe siècle et qui devrait disparaître totalement d'ici 2030 à 2050. La baisse des précipitations neigeuses qui en est responsable est souvent attribuée au réchauffement climatique mais la déforestation est également un facteur majeur.", "Le nom utilisé pour désigner la montagne dans son ensemble est orthographié « Kilimandjaro » en français et Kilimanjaro en anglais. Elle est aussi appelée Ol Doinyo Oibor en maa, soit « Montagne blanche » ou « Montagne étincelante ».", "Image/7 sommets les plus haut du monde/img_q4"),
('Localisez le mont Elbrouz', '7 sommets les plus haut du monde', 43.3499382, 42.44533009999998, "L'Elbrouz ou Elbrous, situé dans le nord du Caucase, en Russie, est le point culminant de cette chaîne de montagnes, avec ses 5 642 mètres il est le plus haut sommet de l'Europe.", "Il s'agit d'un volcan ayant connu des éruptions jusqu'au début de notre ère, et il a fait naître des légendes comme celle voulant que Prométhée ait été enchaîné à ses deux pics principaux pour avoir offert le feu aux hommes.", "Il est recouvert de nombreux glaciers et, même si l'ascension est techniquement facile et dispose de moyens mécaniques sur l'itinéraire principal, il reste difficile d'accès en raison de ses conditions climatiques rigoureuses et changeantes.", "Image/7 sommets les plus haut du monde/img_q5"),
('Localisez le mont Vinson', '7 sommets les plus haut du monde', -78.6340646, -85.21348920000003, "Le massif Vinson, ou mont Vinson pour désigner au sens strict son plus haut sommet, est le point culminant de l'Antarctique avec 4 892 mètres d'altitude1,2,11. Découvert en 1958 au cours d'un survol aérien2, il n'a été gravi qu'en 1966 par Nicholas Clinch et trois autres alpinistes5. Depuis, environ 1 100 personnes ont atteint son sommet2, qui doit sa renommée à son inclusion dans la liste des sept sommets, laquelle regroupe les points culminants des sept continents5.", "Découvert en 1958 au cours d'un survol aérien, il n'a été gravi qu'en 1966 par Nicholas Clinch et trois autres alpinistes.", "Depuis, environ 1 100 personnes ont atteint son sommet, qui doit sa renommée à son inclusion dans la liste des sept sommets, laquelle regroupe les points culminants des sept continents.", "Image/7 sommets les plus haut du monde/img_q6"),
('Localisez la pyramide de Carstensz (Puncak Jaya)', '7 sommets les plus haut du monde', -4.0845986, 137.1866179, "Le Puncak Jaya ou pyramide Carstensz est une montagne d'Indonésie située sur l'île de Nouvelle-Guinée, dans la province de Papouasie. Ses 4 884 mètres d'altitude font de cette montagne le point culminant de l'Indonésie et de l'Océanie, ce qui l'inscrit dans la catégorie des sept sommets, et place la Nouvelle-Guinée en première position dans le classement des îles par altitude.", "Découverte par le Néerlandais Jan Carstenszoon en, la montagne n'est approchée qu'au début du XXe siècle et n'est gravie qu'en 1962 en raison de sa relative inaccessibilité6.", "La présence du Puncak Jaya dans la liste des sept sommets attire cependant de nombreux alpinistes désireux de gravir les points culminants des sept continents. Le Puncak Jaya et les sommets voisins sont un des rares endroits à présenter des glaciers sous des latitudes équatoriales.", "Image/7 sommets les plus haut du monde/img_q7");


INSERT INTO `QUESTIONNAIRES` (`nom_questionnaire`) VALUES
('7 plus hauts gratte-ciels du monde');

INSERT INTO `QUESTIONS` (`intitule`, `nom_questionnaire`, `latitude`, `longitude`,`titre_carousel`, `information1`, `information2`, `information3`) VALUES
('Localisez Burj Khalifa', '7 plus hauts gratte-ciels du monde', 25.1975148, 55.2748732, "Burj Khalifa est la plus grande tour du monde. Appelée Burj Dubaï jusqu’à son inauguration, il s'agit d'un gratte-ciel situé à Dubaï aux Émirats arabes uni.", "Devenu en mai 2009 la plus haute structure humaine jamais construite. Sa hauteur finale, atteinte le 17 janvier 2009, est de 830 mètres. Elle doit former le cœur d’un nouveau quartier : Downtown Burj Khalifa. Son inauguration et ouverture partielle ont eu lieu le 4 janvier 2010.", "La version finale compte 160 étages « habitables ». L’architecture et l’ingénierie de la plus grande tour du monde ont été conçues par Skidmore, Owings and Merrill de Chicago. Adrian Smith en a été l’architecte en chef et Bill Baker en a été l’ingénieur en chef pour le calcul des structures.","Image/7 plus hauts gratte-ciels du monde/img_q1"),
('Localisez Shanghai Tower', '7 plus hauts gratte-ciels du monde', 31.233518, 121.50561700000003, "La tour Shanghai est un gratte-ciel du quartier financier de Pudong à Shanghai. L'immeuble, qui s’élève à une hauteur de 632 mètres, a 128 étages et développe une surface de 420 000 mètres carrés. ", "En 2016, c'est la troisième plus haute structure construite par l'homme, derrière la Burj Khalifa de Dubai (828 mètres), et la Tokyo Sky Tree de Tokyo (634 mètres). C'est le deuxième plus haut gratte-ciel du monde, puisque la Tokyo Skytree est une tour de radiodiffusion.", "L’aménagement urbain du quartier financier de Lujiazui datant de 1993 planifiait trois gratte-ciel géants les uns à côté des autres. La Jin Mao Tower a été achevée en 1998 et le Shanghai World Financial Center en 2008.", "Image/7 plus hauts gratte-ciels du monde/img_q2"),
('Localisez One World Trade Center', '7 plus hauts gratte-ciels du monde', 40.7127431, -74.01337949999999, "Le One World Trade Center (ou 1 World Trade Center ou 1 WTC ; le bâtiment actuel a été surnommé Freedom Tower au début des travaux) est le principal bâtiment du nouveau complexe World Trade Center dans le Lower Manhattan, à New York, et le plus haut gratte-ciel de l'hémisphère ouest. ", "Cette tour de 104 étages porte le même nom que la tour jumelle nord du World Trade Center initial, détruite lors des attentats du 11 septembre 2001.", "Elle se situe dans le coin nord-ouest du site du World Trade Center (d'une surface de 6,5 ha), à l'emplacement de l'ancien World Trade Center. Elle est entourée à l'ouest par West Street, au nord par Vesey Street, au sud par Fulton Street et à l'est par Washington Street.", "Image/7 plus hauts gratte-ciels du monde/img_q3"),
('Localisez Tour Petronas', '7 plus hauts gratte-ciels du monde', 3.1577405, 101.71216700000002, "Les tours jumelles Petronas de Kuala Lumpur en Malaisie ont été conçues par l’architecte argentin Cesar Pelli et inaugurées en 1998. Elles comportent 88 étages pour une hauteur totale de 452 mètres.", "Une passerelle d’acier accessible aux visiteurs relie les deux tours à 170 mètres du sol au niveau des 41e et 42e étages.", "En plus des bureaux du géant pétrolier malais Petronas, cet édifice contient 1,7 million de mètres carrés de boutiques et lieux de divertissement, une salle de concert, une mosquée, ou encore un centre de conférence multimédia. L'ingénieur est Thornton Tomasetti.", "Image/7 plus hauts gratte-ciels du monde/img_q4"),
('Localisez World Financial Center', '7 plus hauts gratte-ciels du monde', 31.2346983, 121.50755879999997, "Le World Financial Center est un complexe de bâtiments situé dans le quartier de Battery Park City, dans Lower Manhattan à New York. Le complexe est bordé à l'ouest par l'Hudson River, à l'est par West Street, et se trouve à proximité du site du World Trade Center et du Financial District.", "Le World Financial Center se compose de quatre bâtiments principaux, le One World Financial Center, le Two World Financial Center, le Three World Financial Center et le Four World Financial Center, reliés entre eux par le Winter Garden.", "Le complexe abrite le siège de nombreuses entreprises liées plus ou moins directement à la finance, parmi lesquelles Merrill Lynch et American Express, ainsi que Dow Jones & Company et le Wall Street Journal. L'intégralité du complexe est possédée par l'entreprise immobilière Brookfield Properties, basée à Toronto.", "Image/7 plus hauts gratte-ciels du monde/img_q5"),
('Localisez Makkah Clock Royal Tower', '7 plus hauts gratte-ciels du monde', 21.4187514, 39.82555639999998, "L'ensemble a été construit à l'emplacement de la forteresse d'Ajyad, un ancien fort de l'époque ottomane datant du XVIIIe siècle, qui a été rasé sur ordre du gouvernement saoudien deux ans avant le début des travaux, en 2002. En outre, la colline sur laquelle cette fortification était bâtie, la montagne de Bulbul, a également été rasée.", "L'architecte était la société libanaise Dar Al-Handasah et le coût du projet s'estima à 1,6 milliard de dollars.", "La plus haute de ces tours, la Makkah Clock Royal Tower mesure 601 mètres de haut, ce qui en fait (en 2016) la quatrième plus haute construction au monde après la Burj Khalifa de Dubaï (829 mètres), la Tokyo Skytree (634 mètres) de Tokyo et la tour Shanghai (632 mètres). L'édifice, qui abrite un hôtel, a ouvert ses portes en 2010.", "Image/7 plus hauts gratte-ciels du monde/img_q6"),
('Localisez Lotte World Tower', '7 plus hauts gratte-ciels du monde', 37.5127779, 127.10257019999995, "D'une hauteur de 555 mètres, le bâtiment était lors de son ouverture en 2017 le cinquième plus haut gratte-ciel du monde.", "Le premier coup de pioche avait été donné en 2005, mais du fait des restrictions de hauteur imposées par la proximité de l'aéroport, les travaux avait été reportés jusqu'en février 2010, après la levée des restrictions en 2009.", "Le 123e et dernier étage a été achevé en décembre 2015.", "Image/7 plus hauts gratte-ciels du monde/img_q7");


/*INSERT INTO `QUESTIONNAIRES` (`nom_questionnaire`) VALUES
('7 volcans les plus gros du monde');

INSERT INTO `QUESTIONS` (`intitule`, `nom_questionnaire`, `latitude`, `longitude`,`titre_carousel`, `information1`, `information2`, `information3`) VALUES
('Localisez le Kilauea', '7 volcans les plus gros du monde', 19.4068929, -155.2833786, "", "", ""),
('Localisez le Etna', '7 volcans les plus gros du monde',37.751005, 14.993434900000011, "", "", ""),
('Localisez le Piton de la Fournaise', '7 volcans les plus gros du monde',-21.242499, 55.70888930000001, "", "", ""),
('Localisez le Kawah Ijen', '7 volcans les plus gros du monde',-8.0584134, 114.24127880000003, "", "", ""),
('Localisez le Taal', '7 volcans les plus gros du monde', 14.0112531, 120.99769089999995, "", "", ""),
('Localisez le Vésuve', '7 volcans les plus gros du monde', 40.82238299999999, 14.428905799999939, "", "", ""),
('Localisez le Sakurajima', '7 volcans les plus gros du monde', 34.6621783, 135.42867539999997, "", "", "");*/